In [2]:
import numpy as np

In [31]:
arr = np.array(np.random.randint(1,10, size=(3,3,2)))
arr2 = np.array(np.arange(1,13))
arr2 = arr2.reshape((4,3) ,order='F')
print(arr2)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [63]:
testarray = np.array([1,7,9,12,13,7,8,11,12,3,11,4,3,1,15,1,3,2,6,5,21,12,4,3])
testarray = testarray.reshape((4,3,2), order='C')
print(testarray)

[[[ 1  7]
  [ 9 12]
  [13  7]]

 [[ 8 11]
  [12  3]
  [11  4]]

 [[ 3  1]
  [15  1]
  [ 3  2]]

 [[ 6  5]
  [21 12]
  [ 4  3]]]


In [66]:
print(testarray.reshape((6,4), order = 'F'))

[[ 1 15  7  1]
 [ 8 21 11 12]
 [ 3 13  1  7]
 [ 6 11  5  4]
 [ 9  3 12  2]
 [12  4  3  3]]
