In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,51,(3,4,2))
arr

array([[[ 6, 23],
        [33, 15],
        [37, 32],
        [ 4, 23]],

       [[14,  7],
        [30, 21],
        [15, 29],
        [46, 32]],

       [[47,  9],
        [22, 27],
        [32, 25],
        [17, 47]]])

In [5]:
import scipy as sc

ModuleNotFoundError: No module named 'scipy'

In [7]:
arr = np.array([2,5,9,3,8,10])

count = 0
def calc_mean(arr):
    for i in arr:
        count = i + (1/i)
    n = len(arr)
    return n/count

calc_mean(arr)

0.594059405940594

In [25]:
arr = np.arange(5,95,5).reshape(3,2,3)
print(arr)
print("arr[-3]\n", arr[-3])
print("\n",arr[-1, 1:3])
print(arr.strides)

[[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]

 [[65 70 75]
  [80 85 90]]]
arr[-3]
 [[ 5 10 15]
 [20 25 30]]

 [[80 85 90]]
(24, 12, 4)


In [51]:
arr1 = np.arange(12)
arr2 = np.reshape(arr1,(4,3),order='F')
print(arr2)
arr3 = np.arange(16).reshape(4,4)
#arr3
print(np.split(arr2, [1,3], axis=1))
arr1

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[array([[0],
       [1],
       [2],
       [3]]), array([[ 4,  8],
       [ 5,  9],
       [ 6, 10],
       [ 7, 11]]), array([], shape=(4, 0), dtype=int32)]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr3 = np.arange(16).reshape(4,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])
out_array = np.empty((3,2))
arr3 = np.vstack((arr1, arr2))
arr4 = np.hstack((arr1, arr2))
np.stack((arr1, arr2), axis =1 ,out=out_array)
print (arr3)
print (arr4)
print (arr5)
print(out_array)

[[2 5 1]
 [3 6 2]]
[2 5 1 3 6 2]
[[2 3]
 [5 6]
 [1 2]]
[[2. 3.]
 [5. 6.]
 [1. 2.]]


In [ ]:
np.concatenate()

In [68]:
import pandas as pd

# create a sample dataframe
df = pd.DataFrame({'A': [1, 4, 3, 2, 5],
                   'B': ['A', 'B', 'C', 'D', 'E']})
df


A  B
0  1  A
1  4  B
2  3  C
3  2  D
4  5  E

In [69]:
# randomly sample one row from the dataframe
sample = df.sample()

print(sample)

   A  B
3  2  D


In [70]:
smallest = df.nsmallest(3, 'A')
smallest

A  B
0  1  A
3  2  D
2  3  C

In [ ]:
df.nsmallest(3, 'A') #here 3 means show 3 rows and 'A' is the col lable 
df.nlargest(3, 'A')  #here 3 means show 3 rows and 'A' is the col lable
sort = df.sort_values('A', kind='quicksort',ascending=True) #by default ascending=True

In [72]:
# select the two largest values in column 'A'
largest = df.nlargest(3, 'A')
largest

A  B
4  5  E
1  4  B
2  3  C

In [77]:
# select the two largest values in column 'A'
sort = df.sort_values('A', kind='quicksort',ascending=True)
sort

A  B
4  5  E
1  4  B
2  3  C
3  2  D
0  1  A