### Numpy Practice

### 1-D

In [3]:
import numpy as np

In [25]:
arr = np.array([12,13, 123, 3+4j, 34.3, "fd", True])
arr

array(['12', '13', '123', '(3+4j)', '34.3', 'fd', 'True'], dtype='<U64')

In [7]:
17 * 9

153

In [8]:
-17 << 3

-136

In [27]:
arr[1,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [15]:
arr.dtype

dtype('int32')

In [16]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [23]:
# Create a 0-D numpy array using array() constructor
arr1 = np.array(10)
print("array: ", arr1)

array:  10


In [24]:
arr[1,1]

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [34]:
ar = np.arange(10, 1, -2)
ar

array([10,  8,  6,  4,  2])

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [36]:
ar = "StringIsTheBakwaas"
a = ar[10:2:-1]
a

'ehTsIgni'

In [44]:
ar = "StringIsTheBakwaas"
a = ar[-3:10:-1]
a

'awkaB'

In [46]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [54]:
a = [1,2,3,4,5]
b = a
b.append(2)
id(a), id(b)

(1761159783424, 1761159783424)

In [90]:
a = np.array([2,3,4])
b = a[:]

In [76]:
id(a), id(b)

(1761160152528, 1761160153104)

In [83]:
b=b*2
id(b)

1761160153776

In [86]:
b

array([2, 3, 4])

In [98]:
c = a*2
a*2


array([16, 24, 32])

In [99]:
c

array([16, 24, 32])